/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
declare namespace Jobcan {
  interface JobcanBase {
    /**
     * 合計件数
     */
    count?: number;
    /**
     * next url
     */
    next?: string;
    /**
     * previous url
     */
    previous?: {
      [k: string]: unknown;
    } | null;
    /**
     * 申請書情報を格納した配列
     */
    results?: {
      /**
       * 申請ID
       */
      id?: string;
      /**
       * タイトル
       */
      title?: string;
      /**
       * 申請状況
       */
      status?:
        | "in_progress"
        | "completed"
        | "rejected"
        | "returned"
        | "canceled_after_completion";
      /**
       * フォームID
       */
      form_id?: number;
      /**
       * フォーム名
       */
      form_name?: string;
      /**
       * フォームタイプ
       */
      form_type?: "general" | "expense" | "payment" | "ec_purchase";
      /**
       * `pre_application`:事前申請, settlement:精算
       */
      settlement_type?: "pre_application" | "settlement";
      /**
       * 申請日
       */
      applied_date?: string;
      /**
       * 申請ユーザのスタッフコード
       */
      applicant_code?: string;
      /**
       * 申請ユーザの姓
       */
      applicant_last_name?: string;
      /**
       * 申請ユーザの名
       */
      applicant_first_name?: string;
      /**
       * 申請ユーザの所属グループ
       */
      applicant_group_name?: string;
      /**
       * 申請ユーザの所属グループコード
       */
      applicant_group_code?: string;
      /**
       * 申請ユーザの役職
       */
      applicant_position_name?: string;
      /**
       * 代理申請ユーザの姓
       */
      proxy_applicant_last_name?: string;
      /**
       * 代理申請ユーザの名
       */
      proxy_applicant_first_name?: string;
      /**
       * 関連グループ名
       */
      group_name?: string;
      /**
       * 関連グループコード
       */
      group_code?: string;
      /**
       * 関連プロジェクト名
       */
      project_name?: string;
      /**
       * 関連プロジェクトコード
       */
      project_code?: string;
      /**
       * 現在の承認ステップ
       */
      flow_step_name?: string;
      /**
       * 申請が修正されたことを示す
       */
      is_content_changed?: boolean;
      /**
       * 合計金額
       */
      total_amount?: number;
      /**
       * 支払日
       */
      pay_at?: string;
      final_approval_period?: string;
      /**
       * 最終承認日
       */
      final_approved_date?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }

  interface JobcanResult {
    id: string;
    title: string;
    form_id: number;
    form_name: string;
    form_type: string;
    settlement_type: null;
    status: string;
    applied_date: Date;
    applicant_code: string;
    applicant_last_name: string;
    applicant_first_name: string;
    applicant_group_name: string;
    applicant_position_name: string;
    proxy_applicant_last_name: null;
    proxy_applicant_first_name: null;
    group_name: string;
    group_code: string;
    project_name: null;
    project_code: null;
    flow_step_name: null;
    is_content_changed: boolean;
    total_amount: null;
    pay_at: null;
    final_approval_period: null;
    final_approved_date: Date;
    applicant_group_code: string;
    detail: Detail;
  }

  interface Detail {
    customized_items: CustomizedItem[];
    expense: null;
    payment: null;
    ec: null;
    approval_process: ApprovalProcess;
    viewers: any[];
    default_attachment_files: any[];
    modify_logs: any[];
  }

  interface ApprovalProcess {
    approval_route_modify_logs: any[];
    is_route_changed_by_applicant: boolean;
    steps: Step[];
    after_completion: AfterCompletion;
  }

  interface AfterCompletion {
    comments: any[];
    files: any[];
  }

  interface Step {
    name: string;
    condition: string;
    status: string;
    approvers: Approver[];
    comments: any[];
    files: any[];
  }

  interface Approver {
    status: string;
    approved_date: Date | null;
    approver_name: string;
    approver_code: string;
    proxy_approver_name: null;
    proxy_approver_code: null;
  }

  interface CustomizedItem {
    title: string;
    content: null | string;
    generic_master: null;
    files: null;
    table: null;
  }
  interface V2result {
    count: number;
    next: string;
    previous: null;
    results: V2RequestResult[];
  }

  interface V2RequestResult {
    id: string;
    title: string;
    status: string;
    form_id: number;
    form_name: string;
    form_type: string;
    settlement_type: string;
    applied_date: Date;
    applicant_code: string;
    applicant_last_name: string;
    applicant_first_name: string;
    applicant_group_name: string;
    applicant_group_code: string;
    applicant_position_name: string;
    proxy_applicant_last_name: string;
    proxy_applicant_first_name: string;
    group_name: string;
    group_code: string;
    project_name: string;
    project_code: string;
    flow_step_name: string;
    is_content_changed: boolean;
    total_amount: number;
    pay_at: Date;
    final_approval_period: Date;
    final_approved_date: Date;
  }

  /* type status*/
  type jobcanStatusRequest =
    | "in_progress"
    | "completed"
    | "rejected"
    | "returned"
    | "canceled_after_completion";
}
